### ISSUE TITLE
Unable to export BITRISE_GIT_COMMIT to next workflow

### ISSUE THREAD

**Issue by nningego** [DroidsOnRoids/bitrise-step-trigger-bitrise-workflow#10]
Im using the following from primary workflow, 
hoping to override the commit hash in the workflow its triggering:
```
   - trigger-bitrise-workflow@0.0.6:
        inputs:
        - exported_environment_variable_names: DEPLOY_ENV|BITRISE_GIT_COMMIT
        - api_token: "$BITRISE_API_TOKEN"
        - workflow_id: deploy_to_env
```
I see  DEPLOY_ENV being sent through ok, but BITRISE_GIT_COMMIT doesn't override input variables of the workflow thats triggered. 
Whats the best way to trigger a new workflow with a commit hash?
